# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cac9176b712f2cf87c0e43d03d66480ac35daa8174bfc69ebc7f356cba79fe33601ed06b7e91edb732f2e7b581b13f7cf7fcbe949da02e0f49cb9712221f3ce0

test:
  secret_key_base: fc0a82e9ba98994715b57ef99bbdf368fddf09b6ce54b429f57d6ea73d6fed50ce57f9d3e095d76c3ee3d2bba727890cead0d5abed36e22ddd6fce31adf53249

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
