# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2d8c6dd8db583ac3a8e62511191fa7108f57d53635f09ae389999ba893b87b0df1ca2d3998ee69e816330566c7d57901156d12ec2770e92c577df839f905b2a

test:
  secret_key_base: 7ec91838bd0793e6ff8eab2d911cc8a601e22f24e3cc5559188f6ef0cd1206a1dd92e1cb5cf936fc42b1a621c15b411d8e43f4443e58213ee0ae4ea1eb3148b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
